### ISSUE TITLE
If a track/clock name contains a `[[link]]`, it does not render as a link

### ISSUE THREAD

**Issue by cwegrzyn** [iron-vault-plugin/iron-vault#100]
e.g., in our test vault, Example Vow has name: `I vow to finish this plugin and make it awesome! [[Chapter 01]]`. When you run a progress track command, this generates the following name field in the mechanics node: `name="[[Example Vow|I vow to finish this plugin and make it awesome! [[Chapter 01]]]]"`

When Obsidian renders that, it gives the inner `[[...]]` priority and doesn't regard the outer `[[...]]` as markup.

**Comment by zkat** [comment]
I think... this makes sense and is the right thing to do. As annoying as it is that you have to first click through to Example Vow before you can click through to Chapter 01. Having inline sections of links like that can get really hairy.

**Comment by zkat** [comment]
I think I have a way around this that will fix it in practice. I'll try it out.
