### ISSUE TITLE
Generate mechanics blocks for all commands

### ISSUE THREAD

**Issue by cwegrzyn** [iron-vault-plugin/iron-vault#18]
- [x] Make a Move
- [x] Take/Suffer on meter
- [x] Ask the Oracle
- [x] Create entity (oracle groups)
- [x] Progress track creation
- [x] Progress track advancement
- [x] #113
- [x] Clock creation
- [x] Clock advancement

**Comment by zkat** [comment]
Also: `clock completion/cancellation` and `progress track cancellation/forsaking`

**Comment by zkat** [comment]
see #85, there's now `clock <name> status="added/removed"` and `track <name> status="added/removed"`

**Comment by zkat** [comment]
I've added nodes for asset addition, removal, and upgrades, as well as marking and unmarking impacts.

**Comment by zkat** [comment]
re: asset addition/removal/upgrades, there's now `asset:` (or just `id:path/to/asset`) links that you can use when rendering these nodes :)

**Comment by cwegrzyn** [comment]
Closing this in favor of specific tasks for assets #462 and impacts #463
