### ISSUE TITLE
Allow configuration of filename/dir for entity generation, just like with clocks/tracks

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#186]
it's not very obvious that this is a setting, and there's still no direct way to control file names like there is with clocks/tracks. Let's consistify this a bit.

**Comment by cwegrzyn** [comment]
This is https://github.com/iron-vault-plugin/iron-vault/issues/152 and i have a branch in progress for it!

**Comment by cwegrzyn** [comment]
Oh well, the issues are a little different actually, but i decided to give it the full treatment in the branch, so...
