### ISSUE TITLE
document ironsworn core support

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#250]
* [ ] update docs with new screenshots (I think just the Guide)
* [x] add docs for rulesets and new settings

**Comment by diggity314** [comment]
I was trying to figure out how to change the ruleset to original ironsworn. If you give some tips I may be able to make a PR for the documentation

**Comment by diggity314** [comment]
ah, I found it in settings. Looks like the latest doc files describe this but it just isn't updated on the live site.
https://iron-vault-plugin.github.io/iron-vault/other-features/settings.html
vs
https://github.com/iron-vault-plugin/iron-vault/blob/main/docs/Other%20Features/Settings.md

Looking forward to trying it out!

**Comment by zkat** [comment]
@diggity314 ah I forgot to regen our docs. Try now. :)

**Comment by zkat** [comment]
I don't think there's anything else to be done here, tbh
