### ISSUE TITLE
renaming entities causes their blocks to error due to the entity not being indexed

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#286]
![image](https://github.com/iron-vault-plugin/iron-vault/assets/17535/00f0dc6d-133a-423b-aea1-cc9c78d10c9e)

**Comment by cwegrzyn** [comment]
Hum. Haven't had a chance to actually poke at this. But I wonder if possibly the editor doesn't reprocess all of the markdown blocks on a rename. If it doesn't do that, then we wouldn't get a new filename to pass to the renderer, and so it would be broken until you reload the tab which would recreate the block with the correct file name. That feels a bit buggy on the part of obsidian... but if true, we could probably work around it by subscribing the renderer to the rename event as well, and using that to update its own filename.

Or..... it could just be a bug of my own doing. But wanted to dump this from my brain while eating lunch all the same.
