### ISSUE TITLE
switching between rulesets kills character block depending on frontmatter

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#303]
If you load up a new ruleset and your character sheet's frontmatter is missing a required field, the character blocks will simply fail to render with a big scary error, and unless you know what they mean, you don't know how to fix it. The only way to fix it, then, is to manually edit frontmatter to add the missing fields.

We should consider just adding these fields ourselves if we try to load a character but they're completely missing, with reasonable defaults.

**Comment by cwegrzyn** [comment]
My thought is to implement this behavior just on read (so it fills in the default values in the ValidatedCharacter object). The file would remain unchanged until someone used a command that caused the character file to be written (e.g., adjusting a meter, adding an asset, etc), at which point all of those defaults would be written. This way we don't muck with your character just while you are experimenting with turning things on/off but not actually playing.

**Comment by zkat** [comment]
I like this solution
