### ISSUE TITLE
Don't write out Starforged truths if SI is enabled?

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#337]
Right now, the generate truths command just spits out both, so you have to delete the SF ones by hand. I haven't checked, but maybe there's a "replaces" thing on the truths data?

**Comment by zkat** [comment]
There's not really anything in datasworn about this, apparently.

I think the solution here is going to be to prompt with multiple checkboxes what rulesets to insert truths for.

**Comment by cwegrzyn** [comment]
I wonder if this will be covered by the playset stuff eventually? https://github.com/rsek/datasworn/issues/31

**Comment by cwegrzyn** [comment]
Just asked on that issue!

**Comment by zkat** [comment]
Fixed for now with a quick patch. We can have a bigger thing for playsets.
