### ISSUE TITLE
If you click while dice are still rolling, it seems to abort whatever is happening

### ISSUE THREAD

**Issue by cwegrzyn** [iron-vault-plugin/iron-vault#340]
At least on mobile, when I do something that uses the 3D dice (say, make a move), if I tap while the dice are rolling, it seems to cancel the operation entirely (possibly throwing an exception?). Instead, it should either skip to rendering a final result or just hide the visual roll entirely. In either case, it should proceed with whatever the final roll would be.

cc @zkat

**Comment by zkat** [comment]
I knew about this and thought it was kind of ok but I think you're right. This is an easy fix so I'll just bang it out
