### ISSUE TITLE
New nodes not being properly appended to previous actor/move nodes

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#375]
When adding new nodes in multi-character mode, they don't get appended to either the previous actor node, or the previous move-inside-actor node. They just get shoved in the toplevel.

![Image](https://github.com/iron-vault-plugin/iron-vault/assets/17535/ab69512f-4b5e-4788-a51c-3431f790aab5)

**Comment by cwegrzyn** [comment]
Huh. What's the KDL for the block that is generated? How many characters do you have, and which was active when you ran the command?

**Comment by cwegrzyn** [comment]
Ohhh. This is a reroll. I intentionally left this as not actor aware (and left a note to that effect). But my reasoning was a bit off-- because not making it actor aware means it won't ever thread into any actor move. Oops!

**Comment by zkat** [comment]
I can’t text right now but I’m pretty sure other things weren’t threading in either? I’ll have to check
