### ISSUE TITLE
Use `datasworn:` or `ds:` scheme for Datasworn ID links

### ISSUE THREAD

**Issue by cwegrzyn** [iron-vault-plugin/iron-vault#383]
Some Datasworn IDs are not valid as URIs, because the part before the colon includes an underscore,
whcih is not valid in URI schemes. (e.g., `oracle_rollable:xyz`).

One solution would be to use links with a consistent scheme prefix like `datasworn:`. To avoid
another ID migration, would could, for now, support both w/ and w/o the scheme-- but always
generate with the scheme. Unless Datasworn implements this format for its markdown, we'd also
need to preprocess all Datasworn markdown to update the link format.

**Comment by zkat** [comment]
Update: datasworn 0.1.0 has been updated, and links now have this prefix.
