### ISSUE TITLE
active character not persisting?

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#401]
something's up with localSettings. I don't think they're saving/loading properly? I keep having to set the active character on every launch.

**Comment by cwegrzyn** [comment]
Is this on the multi-campaign branch?

**Comment by zkat** [comment]
No it’s on the current release

**Comment by cwegrzyn** [comment]
Ah okay. The whole local settings and active character flow are heavily revised in multi campaign so it's worth checking there. Might be moot.

**Comment by zkat** [comment]
annoyingly: I can't repro this on the test vault (I have yet to try it on a fresh vault on Linux. It was failing earlier on Windows)

**Comment by zkat** [comment]
This seems to have been fixed with all the new campaign stuff. Phew!
