### ISSUE TITLE
Support for "enhance asset" in asset attributes

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#417]
Some assets, such as Sundered Isles' `CREW COMMANDER`, have an attribute that, when checked, alters the asset itself. In this case, the `COMMAND` control goes from 4 max to 6 max.

This might be fairly easy to implement or it might be tricky, depending on how it's done, but I think the easiest way is to just do it right in the asset renderer and do some shenanigans where the asset enhancement gets deep-merged in as-is. I think this will be good enough?

**Comment by cwegrzyn** [comment]
Hmm, I think if we put this somewhere in the character asset lens stack we can have a single source of truth where assets have active enhancements applied. Don't forget that we will want this other places too-- like in determining valid values in take/suffer on meter commands.
