### ISSUE TITLE
"Generate an entity" incomplete for Sundered Isles, will not output block

### ISSUE THREAD

**Issue by themaster567** [iron-vault-plugin/iron-vault#453]
Here is what is shown when you try to generate a settlement with Sundered Isles content:
![image](https://github.com/user-attachments/assets/82cc17c2-3f2a-478d-9272-0d27f5beeefb)

And here is what is seen if you try to do it with vanilla Starforged:
![image](https://github.com/user-attachments/assets/65fe756a-1c50-49be-870a-dcf61a96ef6e)

As you can see, several bits are missing on the former, making the entirety of the output completely useless for its intended job of outputting a block. I can screenshot it and manually enter it by hand afterward, but that's _all_ I can do.

**Comment by zkat** [comment]
I'm not seeing the same thing.

Is it possible that your screen is small in the first instance, and you're not scrolling down to where the other fields are, along with the "accept" button etc?

![Screenshot 2024-08-01 113009](https://github.com/user-attachments/assets/f018da8e-b847-41fb-b75d-466f59e3de49)

![image](https://github.com/user-attachments/assets/20b355d6-71f9-4a48-b43e-2d9da8395ebe)

**Comment by themaster567** [comment]
I tried turning off the theme, adjusting the font size, and zooming out, but my 1440p maximized window is still not showing it.
![image](https://github.com/user-attachments/assets/efe750f3-6793-4dd6-95df-f88907d1cc73)

**Comment by zkat** [comment]
weird.

Would you mind doing Ctrl+shift+i and seeing if there's any error messages in the console?

**Comment by themaster567** [comment]
That was the right call. Opening the console shows that the Supercharged Links plugin, something I never would have suspected, constantly throwing errors that all basically look like this:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'plugin')
    at fetchTargetAttributesSync (plugin:supercharged-links-obsidian:613:18)
    at updateDivExtraAttributes (plugin:supercharged-links-obsidian:674:27)
    at eval (plugin:supercharged-links-obsidian:764:17)
    at t.iterateLeaves (app.js:1:2271987)
    at t.eval (plugin:obsidian-hover-editor:18:6826)
    at t.k [as iterateLeaves] (plugin:obsidian-hover-editor:14:13211)
    at t.iterateLeaves (app.js:1:2272085)
    at t.eval (plugin:obsidian-hover-editor:18:6826)
    at t.k [as iterateLeaves] (plugin:obsidian-hover-editor:14:13211)
    at t.iterateLeaves (app.js:1:2272085)
```

Disabling the plugin solves the issue. No idea why it conflicts with only that block specifically, but I wasn't using its features anyway so I can just toss it.

I'm considering closing as solved, especially since it has nothing to do with your plugin, but rather a bad interaction with another. Maybe include the plugin in a list of things that are incompatible. I'll leave it open for now in case you want me to diagnose things any further though.

**Comment by zkat** [comment]
Yeah it’s probably already not compatible because we do our own messing around with link types

**Comment by themaster567** [comment]
It might still be a plugin, but I am having an issue with specifically generating an NPC using the Sundered Isles in the same manner as the issue above. This time I tested all other entities, and with just starforged and sundered isles enabled, only the generate sundered isles NPC box is missing sections. The error log only shows errors with Iron Vault and nothing else, and I don't have anything else that alters those windows. I still disabled a few things regardless for no change. The following are the errors that Iron Vault is throwing the very instant I bring up the generation box:
![image](https://github.com/user-attachments/assets/95964544-0187-4254-8b84-b97675e97854)

And here is the box itself:
![image](https://github.com/user-attachments/assets/21b1a8e6-a05f-4f0c-bcb4-6c5d0e859024)

**Comment by zkat** [comment]
Oh this one makes more sense. Just an outdated id. I’ll take a look later. It should be a quick fix :)

**Comment by themaster567** [comment]
Glad to have helped!
