### ISSUE TITLE
Sidebar fails to render on the mobile device

### ISSUE THREAD

**Issue by YBogomolov** [iron-vault-plugin/iron-vault#469]
Hi! First of all, thank you for your hard work and awesome plugin!

I’ve got an issue where the sidebar with character sheet, moves, and oracles fails to render on the phone. It works fine on desktop and tablet with the same vault.

Platform: iOS 18.0.1
Versions: Obsidian 1.7.4, Iron Vault 1.8.5

How it looks:

![IMG_5044](https://github.com/user-attachments/assets/34a73ca0-33db-4073-99b7-416bde438a62)

Please let me know if I can do something to help with diagnosis of this issue.

**Comment by YBogomolov** [comment]
And after sync it fails to render on the iPad as well:

![IMG_0182](https://github.com/user-attachments/assets/7fb9d785-afbf-4cf8-9994-2e22e18132f1)

I wonder if reinstallation helps. Will check and report.

**Comment by YBogomolov** [comment]
Nope, reinstallation and force-reloading doesn’t help.

**Comment by cwegrzyn** [comment]
My guess is that it is related to these newfangled [deferred views](https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views) added in the new obsidian release

**Comment by YBogomolov** [comment]
@zkat sure, I’ll see if I can get some details. Sorry for getting back only today, I was on a business trip. I think I will have some time for debugging this weekend.

**Comment by cwegrzyn** [comment]
Hmm, I might have resolved the issue where it does render at all (for me it was happening when I had a different sidebar view active, switched tabs, and then activated the iron vault sidebar).

However, I'm still having intermittent trouble with the character sheet tab rendering, so keeping this open.
